root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "./tmp/main"
  delay = 10000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]